dvision:
  camera:
    debug:                 false
    device:                /dev/video1
    width:                 640
    height:                480
    frameRate:             30

    saturation:            64
    contrast:              32
    brightness:            0
    hue:                   0
    gamma:                 100
    gain:                  0
    sharpness:             2

    exposure_auto:         1 # 0 is auto, 1 is manual
    exposure_absolute:     220

    whitebalance_auto:     1
    whitebalance_absolute: 3730

    focus_auto:            1
    focus_absolute:        0




  projection:
    fx:                    363.5620076330466
    fy:                    363.5194666723943
    cx:                    304.7477442613776
    cy:                    236.4042697060596
          #     fx:                    362.3151346254978
          #     fy:                    363.9196105008180
          #     cx:                    244.1087213602206
          #     cy:                    258.8006679840781
    dist_coeff:             
               [1.49379,
               0.104714,
               0.000138179,
               0.000647544,
               -0.0229825,
               1.85803,
               0.537032,
               -0.0533848,
               -0.00181524,
               0.000308373,
               -0.000768987,
               0.000121882,
               -0.00100928,
               0.000758951]
#                             [-1.99874,
#                             0.750843,
#                             -0.000142381,
#                             0.00208654,
#                             0.265364,
#                             -1.64267,
#                             -0.0377996,
#                             0.703062,
#                             -0.0256949,
#                             0.00745481,
#                             0.00170937,
#                             -0.000119779,
#                             0.00136841,
#                             -0.015137]

    extrinsic_para: [
            -3.2479,
            0.065072,
            54.7282,
            0.0074467,
            -0.20784,
            -0.016118,
            2.8422,
            0.57211,
            6.344,
            0.013714,
            -0.012078,
            0.02624,
            1.0076,
            1.0007,
            0.012026,
            0.041972
    ]
# Update interal parameters at 23 July
