dmotion:
    leftKick:
        data:
             [60   , 40    , 25, 50,
              0     , 0      ,  -0.5     , 0.0,    # cmx
              23.0  ,  23.0  ,  23.0   , 23.0,     # cmz
              6     , 7.0      ,  6.5      , 6.5,  # cm roll
              10     , 10      ,  -10      , 0,    # cm pitch
              -5.0  , -5.0   ,   -5.0  , -5.0,     # cm dy
              0     , -0     ,  -0     , 0,        # la x
              0     , 2      ,   4      , 0,        # la y
              0.4    , 3.6      ,   3.5      , 4.0,  # la z
              0     , 10     ,  10     , 10,       # la roll
              -2     , 11    ,  20    , -2,          # la pitch 
              -2    , -2     ,  -2     ,   -2,     # ra pitch 
              20    , 20     ,  20     , 20,
              0     , 0      ,  0      , 0, 
              20    , 20     ,  -40     , -40,
              0     , 0      , -50     ,-50,
              0, 0, 0.3, 0
              ]
        row: 17
        hip:  -55
        knee: -55
        ankle: -60
        ratio: 0.5
        debug: false
    rightKick:
        data:
            [80   ,   40  ,    25   ,  80,           # ticks
              0    ,  0    ,  -0.5        ,0.0,         # cm x
              23 , 23  ,   23     , 23,              # cm z
              -6 ,  -7,    -7,      -7,              # cm roll
              10    ,   10   ,  -10      ,    5,     # cm pitch
              5.2    ,   5.0 ,  5.0    , 5.0,        # cm dy
              0    ,  0   ,  0     ,  0,             # ra x
              0    ,  -2    ,  -4      ,  0,           # ra y
              0  ,   3.3 ,     3.5 ,    3.0,         # ra z
              0    ,   -10 ,  -10    ,  -10,         # ra r
              -2    ,   13   ,   15     ,   -2,      # ra p
              -2   ,  -2   ,  -2     ,  -2,          # la p
              0    ,  0    , 0       , 0,
              0    ,  0    ,  0      ,0,
              0    , 0     ,55       ,55,
              0    , 0     ,55      ,  55,
              0, 0,  0.3, 0
             ]
        row: 17
        hip:  -55
        knee: -55
        ankle: -60
        ratio: 0.5
        debug: false
