dvision:
    amcl:
        enable:            true
        num_particles:     300
        alpha_slow:        0.00001
        alpha_fast:        0.1
        resample_interval: 10
        dist_threshold:    50
        z_hit:             0.95
        z_rand:            0.05
        sigma_hit:         0.2
        max_occ_dist:      20
        good_dist_th:      30
        good_angle_th:     5
        c_step_cost:       0.0005
