dvision:
  camera:
    debug:                 false
    device:                /dev/video0
    width:                 640
    height:                480
    frameRate:             30

    saturation:            64
    contrast:              32
    brightness:            0 
    hue:                   0
    gamma:                 100
    gain:                  0
    sharpness:             0

    exposure_auto:         0 # 0 is auto, 1 is manual
    exposure_absolute:     150

    whitebalance_auto:     1
    whitebalance_absolute: 3730

    focus_auto:            1
    focus_absolute:        0


  projection:
    fx:                    359.8210099657566
    fy:                    359.6130623478990
    cx:                    316.2749319523564
    cy:                    238.6773176146922

    dist_coeff:           
                            [-13.3153,
                            44.1635,
                            0.00327741,
                            0.00019997,
                            9.37811,
                            -12.9676,
                            39.4678,
                            25.6493,
                            0.0044083,
                            -0.00334654,
                            -0.0219007,
                            0.00662906,
                            0.00908839,
                            -0.000962287]

    extrinsic_para:        [
                            -2.142,
                            0.56074,
                            55.347,
                            -0.0067513,
                            -0.24854,
                            0.0017147,
                            1.8213,
                            -0.58848,
                            7.8137,
                            0.00113,
                            -0.0060839,
                            -0.0027685,
                            1.0011,
                            1.0129,
                            -0.010747,
                            0.029736
]
