dmotion:
    leftKick:
        data:
             [   70 ,      70 ,       25 ,       50 ,  50,        # ticks
                  0 ,       0 ,     -0.2 ,        0 ,   0.0,       # cm x
                 23 ,    23 ,     23 ,     23 ,       23,    # cm z
                  5 ,       5.5 ,        5.5 ,  5.5 ,   4,       # cm roll
                  5 ,       5 ,        -5 ,       10 ,   10,       # cm pitch
               -5.4 ,    -5.5 ,     -5.5 ,     -5.5 ,    -4.0,      # cm dxy
                  0 ,      -4 ,        -4 ,        -4 ,  0 ,       # la x 
                  0 ,       0 ,        0 ,        0 ,    0,      # la y
                2.0 ,     3.3 ,      4.3 ,      4.3 ,  0.5,        # la z
                  0 ,      0 ,       0 ,        0 ,   0 ,      # la roll
                  0 ,       2 ,       2 ,        2 ,    -2 ,     # la pitch
                 -2 ,      -2 ,       -2 ,       -2 ,   -2,       # ra pitch
                  0 ,       0 ,        0 ,        0 ,    0,      # 
                  0 ,       0 ,        0 ,        0 ,    0,      #
                  0 ,       0 ,       -40,       -40 ,   0,       # knee
                  0 ,       0 ,       -50 ,       -50 ,  0,        # ankle
                  0 ,       0 ,      0.5 ,        0  ,   0       # delay
              ]
        row: 17
        hip:  -50
        knee: -40
        ankle: -40
        ratio: 0.5
        debug: false
    rightKick:
        data:
             [   70 ,    60  ,   20   ,    50,               # ticks
                  0 ,    0  ,    -1  ,      0,                # cm x
                23.5 ,  23.5   ,   23.5 ,     23.5,             # cm z
                -8.5 ,   -9.5 ,    -9.5 ,    -9.5 ,            # cm roll
                   5 ,   5 ,    0    ,        10,              # cm pitch
                 6.5 ,   6.5 ,  6.5    ,    6.5,               # cm dxy
                   0 ,  -6    ,  0   ,      0,                # ra x
                  -1 ,  -1     ,  0    ,      0,                # ra y
                   0 ,   4 ,     4 ,        0,                 # ra z
                   0 ,  -10 ,    -10     ,   0,              # ra roll
                  -5 ,   10   ,     0     ,    0,              # ra pitch
                  -5 ,  -5   ,    -5     ,    -5,               # la pitch
                   0 ,     0 ,    0  ,        0,               #
                   0 ,     0 ,    0  ,        0,               #
                   0 ,    0 ,    30  ,       30,               # knee
                   0 ,    0 ,    55      ,   55,               # ankle
                   0 ,    0 ,     0.6 ,     0
             ]
        row: 17
        hip:  -50
        knee: -40
        ankle: -40
        ratio: 0.5
        debug: false
